CREATE TABLE "croc_admin_mails" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "croc_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"role" varchar DEFAULT 'user',
	"fname" varchar(255),
	"lname" varchar(255),
	"phone" varchar(20),
	"city" varchar(255),
	"address" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "croc_image" (
	"id" serial PRIMARY KEY NOT NULL,
	"utID" varchar(255),
	"utURL" varchar(2048),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "croc_category" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar NOT NULL,
	"slug" varchar NOT NULL,
	"description" varchar,
	"sort_order" serial NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"category_img_id" integer,
	CONSTRAINT "croc_category_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "croc_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "croc_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"total_price" integer DEFAULT 0 NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"discount" integer DEFAULT 0,
	"note" varchar,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"userID" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "croc_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "croc_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"price" integer NOT NULL,
	"quantity" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"orderID" integer NOT NULL,
	"productID" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "croc_product" (
	"id" serial PRIMARY KEY NOT NULL,
	"sort_order" serial NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"purchase_price" integer NOT NULL,
	"sale_price" integer NOT NULL,
	"stock" integer DEFAULT 0 NOT NULL,
	"description" text,
	"meta_title" text,
	"meta_description" text,
	"trending" boolean DEFAULT false NOT NULL,
	"new_arrival" boolean DEFAULT false NOT NULL,
	"best_seller" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"category_slug" varchar(255),
	"status_slug" varchar(255),
	CONSTRAINT "croc_product_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "croc_product_image" (
	"id" serial PRIMARY KEY NOT NULL,
	"sort_order" serial NOT NULL,
	"product_id" integer NOT NULL,
	"img_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "product_img_comp_key" UNIQUE("img_id","product_id")
);
--> statement-breakpoint
CREATE TABLE "croc_product_status" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "croc_product_status_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "croc_category" ADD CONSTRAINT "croc_category_category_img_id_croc_image_id_fk" FOREIGN KEY ("category_img_id") REFERENCES "public"."croc_image"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "croc_order" ADD CONSTRAINT "croc_order_userID_croc_user_id_fk" FOREIGN KEY ("userID") REFERENCES "public"."croc_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "croc_order_item" ADD CONSTRAINT "croc_order_item_orderID_croc_order_id_fk" FOREIGN KEY ("orderID") REFERENCES "public"."croc_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "croc_order_item" ADD CONSTRAINT "croc_order_item_productID_croc_product_id_fk" FOREIGN KEY ("productID") REFERENCES "public"."croc_product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "croc_product" ADD CONSTRAINT "croc_product_category_slug_croc_category_slug_fk" FOREIGN KEY ("category_slug") REFERENCES "public"."croc_category"("slug") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "croc_product" ADD CONSTRAINT "croc_product_status_slug_croc_product_status_slug_fk" FOREIGN KEY ("status_slug") REFERENCES "public"."croc_product_status"("slug") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "croc_product_image" ADD CONSTRAINT "croc_product_image_product_id_croc_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."croc_product"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "croc_product_image" ADD CONSTRAINT "croc_product_image_img_id_croc_image_id_fk" FOREIGN KEY ("img_id") REFERENCES "public"."croc_image"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "admin_email" ON "croc_admin_mails" USING btree ("email");--> statement-breakpoint
CREATE INDEX "category_slug_idx" ON "croc_category" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "product_slug_idx" ON "croc_product" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "Product_Category_idx" ON "croc_product" USING btree ("category_slug");--> statement-breakpoint
CREATE INDEX "Product_Status_idx" ON "croc_product" USING btree ("status_slug");--> statement-breakpoint
CREATE INDEX "trending_idx" ON "croc_product" USING btree ("trending");--> statement-breakpoint
CREATE INDEX "new_arrival_idx" ON "croc_product" USING btree ("new_arrival");--> statement-breakpoint
CREATE INDEX "best_seller_idx" ON "croc_product" USING btree ("best_seller");--> statement-breakpoint
CREATE INDEX "img_product_idx" ON "croc_product_image" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "status_slug" ON "croc_product_status" USING btree ("slug");